### PR TITLE
Schemas

### PR DESCRIPTION
**Pull request by bmordan**
Here is an idea.

Could be less verbose if we defaulted to a text field with no validation rules?

### CODE REVIEW

**Comment by richsilv** [comment]
Yeah, I like the idea of defaulting as there will be lots of text fields we could avoid listing.  Similar for validation.

Apart from that it looks ideal. :+1:

**Comment by bmordan** [comment]
OK so you create content in content.json

If you have a content key with a value that is not a text field then you define it in the schema.json like this:

``` json
{
  "jumbotronH1": {
    "type": "text",
    "validation": {
      "max": 65
    }
  },
  "jumbotronLead": {
    "type": "textarea"
  },
  "jumbotronBg": {
    "type": "img"
  }
}
```

if (!content[key]) return {type: 'text'}
sort of thing

**Comment by richsilv** [comment]
Yeah, that's exactly what I was thinking.

**Comment by richsilv** [comment]
:+1:

**Pull request merged**
